name: Deploy
on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish latest image
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: gieseladev/wampus
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: contains(github.ref, 'refs/tags/v')
        name: Publish tagged image
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: gieseladev/wampus
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: "true"